### PR TITLE
Properly cast viewport parameters to ints

### LINKED ISSUE #166: Cannot set viewport
I run mochify with a command likes this `mochify --viewport-height 2000 --viewport-width 2000` and it comes with an error message `(node:65342) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Emulation.setDeviceMetricsOverride): Invalid parameters width: integer value expected; height: integer value expected`

It was ok when I used mochify 3.3.0. The error came when I upgraded to 5.2.0 

I am using 
- mochify 5.20
- node 6.10.3
- mocha 4.1
- browserify 15.2
- puppeteer 1.0

### PR DESCRIPTION
**Pull request by m90**
Should fix #166

### CODE REVIEW

**Comment by m90** [comment]
Should I release this as `5.3.1`?

**Comment by mantoni** [comment]
@m90 Yes please :)

**Comment by VinhVu0412** [comment]
Great work guys!

**Comment by mantoni** [comment]
@VinhVu0412 You're welcome. Thanks for reporting.

**Pull request merged**
