### PR TITLE
nyc support

### PR DESCRIPTION
**Pull request by mantoni**
~~_Work in progress! Do not merge!_~~

This ~~is an attempt to integrate~~ integrates mochify with `nyc`. It works ~~for small projects~~, but requires quite some complicated setup.

It might be a better option to write a custom transform in this project, that uses the recent implementation of the istanbul instrumenter directly.

Ref https://github.com/sinonjs/sinon/issues/1948

### CODE REVIEW

**Comment by mantoni** [comment]
It's quite a hack, but it works fine. I'd go with this for now. I've applied the new instructions in the readme successfully to a small project and to Sinon.JS.

**Comment by mantoni** [comment]
I tried coming up with a test case, but it's really hard, given that the tests are all integration style.

**Comment by mroderick** [comment]
That is indeed an elaborate script

**Comment by mantoni** [comment]
I managed to bring it down by using a nyc config in the `package.json` and by invoking `npm run test-headless` decorated with the additional argument. I just released mochify 6 with all the updates and will send a PR for Sinon now.

**Pull request merged**
