### PR TITLE
Adds support for exclude option to browserify

### PR DESCRIPTION
**Pull request by wesleytodd**
Not sure if there was a better way to do this, because there are plenty of unsupported options from browserify.  But this adds the one I needed.

### CODE REVIEW

**Comment by mantoni** [comment]
Cool thanks. Mind adding a simple test? There are similar ones to copy and adopt.

**Comment by wesleytodd** [comment]
Added.

**Comment by mantoni** [comment]
This is a good test to add, but I was mainly thinking about an integration style test [like this very similar one](https://github.com/mantoni/mochify.js/blob/770be84c5e89f653ad822deb9747046f9634bf87/test/api-test.js#L95). 😃

**Comment by mantoni** [comment]
I would still like to merge this if you could fix the conflict and add that unit test, @wesleytodd ?

**Comment by wesleytodd** [comment]
Hey @mantoni, sorry I have been slammed lately and not able to update this.  I have at least two other things ahead of this on my priority list at the moment, so I don't want to promise anything.  Feel free to take my work without merging.  Or just amend my commit, which github then credits both of us.

**Comment by mantoni** [comment]
Thanks for the update. I don't depend on this myself and I'm also quite busy atm. I'll just leave it open for now.

**Comment by mantoni** [comment]
It's been more than a year. If anyone wants this feauture, please open a new pull request. Thanks!

**Pull request closed without merging**
