### PR TITLE
add support for custom mocha path

### PR DESCRIPTION
**Pull request by boneskull**
Needs changes from mantoni/mocaccino.js#23... more discussion there.

### CODE REVIEW

**Comment by mantoni** [comment]
Thank you! Should be easy to integrate with mocaccino `v4.1.0`. 👍

**Comment by boneskull** [comment]
@mantoni 	not sure if the failure is related..

**Comment by mantoni** [comment]
Apparently it wasn't 😄

**Comment by mantoni** [comment]
Can you add an integration test for this?

**Comment by m90** [comment]
This `coverage dot` test is the bane of mochify's test suite, maybe it would be a thing to find out why it is so flaky.

**Comment by boneskull** [comment]
dot reporter tests have historically been a bane on mocha's side as well

**Comment by boneskull** [comment]
we have moved towards using the JSON reporter for most tests where this level of information is needed

**Comment by boneskull** [comment]
awww who clicked the restart job button

**Comment by boneskull** [comment]
OK, I've added two tests, and should be done w/ this assuming CI passes.

**Comment by mantoni** [comment]
Released in `v6.1.0` 🎈

**Pull request merged**
