### PR TITLE
pass colors through to mocaccino

### PR DESCRIPTION
**Pull request by boneskull**
does what it says on the tin

### CODE REVIEW

**Comment by mantoni** [comment]
Cool! How about some basic tests and mentioning this in the docs?

**Comment by boneskull** [comment]
@mantoni Is mentioning it in the docs necessary?  I figured this was a bug, since it's already mentioned in the docs, but doesn't actually work.

Where's an example of asserting arguments are passed to `mocaccino`?  l

**Comment by mantoni** [comment]
Oh, sorry. I didn't pay enough attention. You're absolutely right, that's a bug. There are no specific tests for passing arguments to moccasino, "only" integration style test cases. Never mind.

**Comment by mantoni** [comment]
Released in `2.11.1`.

**Pull request merged**
