### PR TITLE
fix require parameter add before other entry files

### PR DESCRIPTION
**Pull request by tamascsaba**
When i require other module only add after the tests.

### CODE REVIEW

**Comment by mantoni** [comment]
Hmm. [Browserify adds entries before requires](https://github.com/substack/node-browserify/blob/master/index.js#L88) and I would like to keep the same order.
However, they use the `require` function instead of `add`. Would that work for you as well?

**Comment by tamascsaba** [comment]
I want to run scripts before my tests, only with ``add`` can you run it before.

**Comment by mantoni** [comment]
Well, then you could just specify the scripts as arguments in the correct order:

```bash
$ mochify ./my-setup.js ./test/*.js
```

**Comment by tamascsaba** [comment]
Nice tip :+1:

**Pull request closed without merging**
