### PR TITLE
Update puppeteer dependency

### PR DESCRIPTION
**Pull request by albertyw**
This PR updates puppeteer from `^9.1.1` to `^10.0.0`.  This was done on top of #227 and split from #226.  

This PR was generated by 
1.  checking out master
2. `npm install` (getting to #227)
3. Updating package.json with the new puppeteer version
4. `npm install`

### CODE REVIEW

**Comment by m90** [comment]
@mantoni Do you think this is safe to merge? Considering `npm audit` on Mochify currently has a clean sheet and this brings no extra feature we need I'd maybe play safe (i.e. defer the update) but then again I might be getting too conservative lately.

**Comment by mantoni** [comment]
I guess it's fine. If you have doubts regarding compatibility, this could be a major. But I don't think it breaks anything from a mochify user perspective.

**Comment by m90** [comment]
Ok, then let's merge it and release as 8.1.0 - I just spend way too much time wrestling $NPM_MONSTROSITY at $DAYJOB recently...

@albertyw Could you rebase the branch so it's in a mergeable state again and then we'll ship it?

**Comment by albertyw** [comment]
👍 Rebased

**Comment by m90** [comment]
Published in `8.1.0`, thank you :pray:

**Pull request merged**
