### PR TITLE
add missing output to opts.output

### PR DESCRIPTION
**Pull request by amchang**
The phantom output needs to print out somewhere.

I was scratching my head wondering why no output from my test logs was printing, there is that option already to set the output location, so just print it out now.

### CODE REVIEW

**Comment by mantoni** [comment]
Hmm, most PhantomJS related test cases now fail, some showing the output twice. Can you investigate?

**Comment by amchang** [comment]
Yeah I'll take a look, so weird

**Comment by mantoni** [comment]
Ok, now you're not piping the `min-webdriver` output anymore, right?

**Comment by mantoni** [comment]
Oh, and it's still printing everything twice, but you changed the test cases to ignore that. *haha*

**Comment by mantoni** [comment]
I suggest that you start over with a test case demonstrating the problem first, and then implement a solution that fixes the issue. Honestly, I don't see where the problem with the current implementation is.

For a cleaner history, I would also suggest this to be done in a new PR. What do you think?

**Comment by amchang** [comment]
@mantoni I'm not sure what your looking for, are you looking for a test case of the error?

**Comment by amchang** [comment]
Going to close for now ... I think I might have found the issue. Will reopen the PR if necessary

**Comment by mantoni** [comment]
I was just surprised to hear that the main use case of this tool does not print anything at all for you. That is why I asked you to provide something that reproduces the issue.

Thanks for helping on Mochify! :+1:

**Pull request closed without merging**
